# Generated by Django 2.2 on 2019-04-05 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=100, verbose_name='Adresse')),
                ('tel', models.CharField(max_length=20, unique=True)),
            ],
        ),
    ]
