# Generated by Django 2.2 on 2019-04-06 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestock_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='pseudo',
            field=models.CharField(default='papi', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
